[package]
name = "ptr-metadata"
version = "0.0.0"
authors = ["BD103"]
edition = "2021"
homepage = "https://bd103.github.io/blog/"
repository = "https://github.com/BD103/Blog-Examples"
license = "MIT"
publish = false
